### PR TITLE
Rework errors, rename "cilent" to internals.

### PR DESCRIPTION
**Pull request by angrymouse**

### CODE REVIEW

**Comment by angrymouse** [comment]
Oh idk how did I update readme

**Comment by kunal-saini** [comment]
Hey @angrymouse 

Could you revert the readme changes so I can go ahead merge the pull request!

thanks!

**Comment by angrymouse** [comment]
@kunal-saini Done!

**Comment by kunal-saini** [comment]
thank you @angrymouse for your contribution, I have merged changes into develop and will merge to master with a few feature changes!

**Pull request merged**
